spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: postgres
  application:
    name: gradle-example
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    show-sql: true
  profiles:
    active: local
flyway:
  user: postgres
  password: postgres
  url: jdbc:postgresql://localhost:5432/mydb
  check-location: true
  locations: classpath:db/migration
  enabled: true